# Acronyms List   

**AAHRPP**: Association for the Accreditation of Human Research Protection Program  
**ACCME**: Accreditation Council for Continuing Medical Education  
**ACORP**: Animal Component of Research Protocol  
**ADPAC**: Automated Data Processing Application Coordinator  
**ANCC**: American Nurses Credentialing Center  
**APA**: American Psychological Association  
**ASWB**: Association of Social Work Boards  
**ATS**: Addiction Treatment Services  
**AUD**: Alcohol Use Disorder  
**BHIP**: Behavioral Health Integration Project  
**BISL**: Business Intelligence Service Line  
**CBOC**: Community Based Outpatient Clinic  
**CC**: Care Coordination  
**CFIR**: Consolidated Framework for Implementation Research  
**CHCE**: Center for Health Care Evaluation  
**CPRS**: Computerized Patient Record System  
**CPT Code**: Current Procedural Terminology  
**CRADA**: Cooperative Research and Development Agreement  
**CSP**:  Cooperative Studies Program  
**CTR3**: Center for Tissue Regeneration, Rehabilitation, and Repair  
**CWT**: Comprehensive Work Therapy  
**DEA**: Drug Enforcement Agency  
**DHHS**: Department of Health & Human Services  
**EBP**: Evidence-Based Practices  
**EBPharm**: Evidence-Based Pharmacotherapy  
**EBPsy**: Evidence-Based Psychotherapy  
**EES**: Employee Education Services  
**F&A Rate**: Facilities & Administrative Rate  
**FAR**: Federal Acquisition Regulations  
**FTE**: Full Time Equivalent  
**GHPC**: Georgia Health Policy Center  
**GRECC**: Geriatric Research, Education and Clinical Center  
**HERC**: Health Economics Resource Center  
**HSR&D**: Health Services Research and Development Services  
**IACUC**: Institutional Animal Care and Use Committee  
**INAPS**: International Association of Peer Supporters  
**IOP**: Intensive Outpatient Program
**IPA**: Intergovernmental Personnel Act  
**IRB**: Institutional Review Board  
**JPA**: Joint Personnel Agreement  
**LD**: Livermore Division  
**MAT**: Medication Assisted Therapy
**MHICM**: Mental Health Intensive Case Management
**MHTC**: Mental Health Treatment Coordinators  
**MIRECC**: Mental Illness Research, Education, and Clinical Center  
**MM**: Medication Management  
**MPD**: Menlo Park Division  
**NAVREF**: National Association of Veteran's Research and Education Foundations  
**NBCC**: National Board for Certified Counselors  
**NCPTSD-DT**: National Center for Posttraumatic Stress Disorder, Dissemination & Training  
**NIH**: National Institutes of Health  
**OGC**: Office of General Counsel  
**OMB**: Office of Management & Budget  
**OMHO**: Office of Mental Health Operations (now **OMHSP**)  
**OMHSP**: Office of Mental Health & Suicide Prevention (previously **OMHO**)  
**OPM**: Office of Personnel Management  
**ORO**: Office of Research Oversight  
**OUD**: Opioid Use Disorder  
**PAD**: Palo Alto Division  
**PAIRE**: Palo Alto Institute for Research and Education, Inc.  
**PAVIR**: Palo Alto Veterans Institute for Research  
**PCP**: Primary Care PHysician  
**PCT**: PTSD Clinical Team  
**PE**: Prolonged Exposure  
**PERC**: Program Evaluation and Resource Center  
**PHI**: Protected Health Information
**PI**: Prinicipal Investigator  
**PSA**: Personal Services Agreement  
**PSD**: Participatory System Dynamics  
**QI**: Quality Improvement  
**R&DC**:  Research and Development Committee  
**RDIS**: Research and Development Information System  
**rJPA**: Reverse Joint Personnel Agreement  
**SAIL**: Strategic Analytics for Improvement and Learning  
**Sankey**: A type of flow diagram where the width of the arrows are proportional to the flow quantity  
**"Say File"**: GitHub file for the facilitators to read from  
**"See File"**: GitHub file for learners to look at at  
**SME**: Subject Matter Expert  
**SMI**: Serious Mental Illness  
**SRC**: Scientific Review Committee  
**SRS**: Subcommittee on Research Safety  
**SU**: Stanford University  
**SUD**: Substance Use Disorder  
**UI**: User Interface
**VA**: Veterans Affairs  
**VAPAHCS**: Veterans Affairs Palo Alto Health Care System  
**VAPOR**: Veterans Advisory Partnership for Operations and Research  
**VERC**: Veterans Engineering Resource Center  
**VHA**: Veterans Health Administration  
**VISN**: Veterans Integrated Service Network  
**VISTA**: Veterans Health Information Systems and Technology Architecture  
**WCC**: Women's Counseling Center  
**WRIISC**: War Related Illness & Injury Study Center  
**WRVU**: Work Relative Value Unit
**X Waiver**: Needed to prescribe buprenorphine; must complete training and still limits # of patients per physician that can receive bup  

