---
title: "GitHub User Guide"
author: "Stacey Park"
date: "August 31, 2017; Updated May 22, 2018"
output:
  github_document: default
  html_document: default
  ioslides_presentation: default
  slidy_presentation: default
---

# GitHub User Guide  
### **Creating An Account**  
Create an account if you have not already done so. When creating an account, make a username that doesn't use any spaces, special characters, capital letters, etc.  Just use lowercase letters and underscores if necessary. This is good coding style.  

### **Basics of GitHub**  
Go through the quick guide in the link below. It will teach you how about repositories, branches, commits, and opening/merging pull requests.  
https://guides.github.com/activities/hello-world/

### **Creating Files**  
For syntax and style guidelines, refer to r_markdown_cheatsheet.pdf, which you can find in this branch. Again, name files in all lowercase with underscores as needed. You can also refer to other files in the repository for assistance. To view the file's code, simply click "Raw" in the top right corner of the file, next to "Blame" and "History."  
*Please do not create files in the master branch*

### **Uploading Files**  
To upload files, simply choose the branch that you want to upload to and upload the file. The file will be named as it was in your computer, so make sure to give the file a name that is simple and reflective of its contents to anyone that reads the file name.  
*Please do not upload files to the master branch*

### **Downloading Files**  
Files cannot be downloaded individually - you have to download the entire branch.  You can find the green "Download" button on the main page of each branch.

### **GitHub Workflow**
1. Open the file you want to focus on.  Create a new working branch and name it using all lowercase and no spaces (use underscores).  

<video width="320" height="240" controls>  
  <source src="https://raw.githubusercontent.com/lzim/teampsd/videos/github_workflow_1.mp4" type="video/mp4">  
</video>
https://raw.githubusercontent.com/lzim/teampsd/videos/github_workflow_1.gif
2. 
